---
title: "01.1-methylation-explore"
format: markdown_github
editor: visual
---

```{r, message=FALSE}
library(tidyverse)
```

Bismark + was done on Hyak.

Genmome stats

```{r}
kt <- read.csv("../data/Pver-karytotype.tab", header = FALSE, sep = "\t")
```

```{r}
knitr::kable(head(kt))
```

There are `r nrow(kt)` scaffolds

```{r}
nrow(kt)
```

```{r}
ggplot(kt, aes(x = V2)) +
  geom_histogram(bins = 100) +
  scale_x_log10()
```

```{r, warning=FALSE}
ggplot(kt, aes(x = V2)) +
  geom_histogram(bins = 100) +
  xlim(0, 5000)
```

```{r}
knitr::kable(kt %>% filter(V2 < 1000) %>% count())
```

First thing I want to do is do a simple histogram showing distribution of methylation levels. This will likely be done by taking 10 bedgraphs and concatenating then, making a histogram.

After that I would want to look at distribution across features..

```{bash}
ls ../big-data
```

```{bash}
#cat ../big-data/*10x.bedgraph > ../big-data/merge10x.bedgraph
```

```{bash}
head ../big-data/merge10x.bedgraph
```


```{r}
read.csv("../big-data/12_10x.bedgraph", header = FALSE, sep = "\t") %>%
ggplot(aes(x = V4)) +
  geom_histogram() +
  coord_cartesian(ylim=c(0, 100000))
```


```{r}
read.csv("../big-data/1_10x.bedgraph", header = FALSE, sep = "\t") %>%
ggplot(aes(x = V4)) +
  geom_histogram() +
  coord_cartesian(ylim=c(0, 100000))
```



```{r}
read.csv("../big-data/5_10x.bedgraph", header = FALSE, sep = "\t") %>%
ggplot(aes(x = V4)) +
  geom_histogram() +
  coord_cartesian(ylim=c(0, 100000))
```

```{r}
read.csv("../big-data/16_10x.bedgraph", header = FALSE, sep = "\t") %>%
ggplot(aes(x = V4)) +
  geom_histogram() +
  coord_cartesian(ylim=c(0, 100000))
```