---
title: "03-report"
format: html
editor: visual
---

## 

In order to take an integrative and comparative assessment of multiple epigenetic mechanisms, we have focus on select samples from Acropora pulchra, Porites evermanni, Pocillopora meandrina. Samples have been processed for short RNA, long non-coding RNA, and mRNA.

For short RNA analyses, data was quality trimmed using flexbar followed by ShortStack for identification of microRNA loci.

|                              | Acropora pulchra | Pocillopora meandrina | Porites evermanni |
|------------------------------|------------------|-----------------------|-------------------|
| Trimmed reads (millions)     | 187.8            | 95.8                  | 163.4             |
| Possible sRNA loci in genome | 1284             | 1714                  | 2502              |
| Matched sRNA loci in genome  | 51               | 99                    | 38                |

For each species of the species approximately 10,000 lncRNAs were identified. Inter-species homology comparisons of lncRNAs indicate that A pulchra and P meandrina have about 1000 common lncRNAs, P meandrina and P evermanni have about 500 common lncRNA and A pulchra and P evermanni have about 1000 common lncRNA.
