---
title: "A pulcra kallisto"
author: Steven Roberts
date: "`r format(Sys.time(), '%d %B, %Y')`"  
output: 
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = FALSE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)
```




```{r, engine='bash'}
/home/shared/kallisto/kallisto -h
```

```{r, engine='bash'}
/home/shared/kallisto/kallisto \
index -i \
../data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.index \
../data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.fna
```
```{r, engine='bash'}
ls ../data/S*
```

# Amil2.1


```{r, engine='bash'}
 /home/shared/kallisto/kallisto \
quant -i ../data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.index \
-o ../output/03-kallisto/mil_SRR8601366 \
-t 40 \
../data/SRR8601366_1.fastq ../data/SRR8601366_2.fastq \
2>&1 | tee ../output/03-kallisto/mil_SRR8601366.out
```
```{r, engine='bash'}
 /home/shared/kallisto/kallisto \
quant -i ../data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.index \
-o ../output/03-kallisto/mil02_SRR8601366 \
-t 40 \
--genomebam \
--gtf ../data/Amil/ncbi_dataset/data/GCF_013753865.1/genomic.gff \
../data/SRR8601366_1.fastq ../data/SRR8601366_2.fastq \
2>&1 | tee ../output/03-kallisto/mil02_SRR8601366.out
```


```{r, engine='bash'}
 /home/shared/kallisto/kallisto \
quant -i ../data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.index \
-o ../output/03-kallisto/mil03_SRR8601366 \
-t 40 \
--genomebam \
--gtf ../data/Amil/ncbi_dataset/data/GCF_013753865.1/genomic.gtf \
../data/SRR8601366_1.fastq ../data/SRR8601366_2.fastq \
2>&1 | tee ../output/03-kallisto/mil03_SRR8601366.out
```

# Adig

```{r, engine='bash'}
/home/shared/kallisto/kallisto \
index -i \
../data/Adig/ncbi_dataset/data/GCF_000222465.1/GCF_000222465.1_Adig_1.1_genomic.index \
../data/Adig/ncbi_dataset/data/GCF_000222465.1/GCF_000222465.1_Adig_1.1_genomic.fna
```



```{r, engine='bash'}
 /home/shared/kallisto/kallisto \
quant -i ../data/Adig/ncbi_dataset/data/GCF_000222465.1/GCF_000222465.1_Adig_1.1_genomic.index \
-o ../output/03-kallisto/dig_SRR8601366 \
-t 40 \
../data/SRR8601366_1.fastq ../data/SRR8601366_2.fastq \
2>&1 | tee ../output/03-kallisto/dig_SRR8601366.out
```



# Ahya


```{r, engine='bash'}
/home/shared/kallisto/kallisto \
index -i \
../data/Ahya/ncbi_dataset/data/GCA_020536085.1/GCA_020536085.1_Ahyacinthus.chrsV1_genomic.index \
../data/Ahya/ncbi_dataset/data/GCA_020536085.1/GCA_020536085.1_Ahyacinthus.chrsV1_genomic.fna
```



```{r, engine='bash'}
 /home/shared/kallisto/kallisto \
quant -i ../data/Ahya/ncbi_dataset/data/GCA_020536085.1/GCA_020536085.1_Ahyacinthus.chrsV1_genomic.index \
-o ../output/03-kallisto/hya_SRR8601366 \
-t 40 \
../data/SRR8601366_1.fastq ../data/SRR8601366_2.fastq \
2>&1 | tee ../output/03-kallisto/hya_SRR8601366.out
```







# Comparing alignment rates

```{r, engine='bash', eval=TRUE}
grep 'p_' ../output/03-kallisto/dig_SRR8601366/run_info.json
```


```{r, engine='bash', eval=TRUE}
grep 'p_' ../output/03-kallisto/mil_SRR8601366/run_info.json
```

```{r, engine='bash', eval=TRUE}
grep 'p_' ../output/03-kallisto/mil02_SRR8601366/run_info.json
```

```{r, engine='bash', eval=TRUE}
grep 'p_' ../output/03-kallisto/mil03_SRR8601366/run_info.json
```




```{r, engine='bash', eval=TRUE}
grep 'p_' ../output/03-kallisto/hya_SRR8601366/run_info.json
```





```{r, engine='bash', eval=TRUE}
echo "A hyacinthus"
grep 'p_' ../output/03-kallisto/hya_SRR8601366/run_info.json
echo "A millipora"
grep 'p_' ../output/03-kallisto/mil_SRR8601366/run_info.json
echo "A digitera"
grep 'p_' ../output/03-kallisto/dig_SRR8601366/run_info.json
```