---
title: "TE_in_piRNA_clusters"
author: "Javier Rodriguez Casariego"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = '/Users/jarcasariego/Dropbox/Other_projects/E5_work/deep-dive/D-Apul/')
```


```{r}
#This script generates stacked barplots comparing TE content in the entire genome to that of piRNA clusters
#load libraries
library(dplyr)   
library(ggplot2)
library(tidyverse)

my.outprefix <- paste(Sys.Date(),"Cluster",sep="_")

#read in the outfile from repeatmasker
out_file <- read.table("data/Amil/GCF_013753865.1_Amil_v2.1_genomic.fna.out", comment.char = "", header = F, fill = T, skip = 2)

#retains only 1)chromosome 2)start 3)stop 4)TE name 5)Family Name
bed_file <- out_file[,c(5:7,10:11)]

#Assess how the families breakdown for the whole genome
#remove empty lines 
bed_file <- bed_file %>%
  drop_na(.)

#output bed file
write.table(bed_file, file = "output/18.2-Apul-piRNA-TE-overlap/APUL_repeatmasker_bedfile.bed", sep = "\t", col.names = F, row.names = F, quote = F)

#retain only major family name and combine unclear and Unknown
bed_file$V11 <- gsub("/.*","",bed_file$V11)
bed_file$V11 <- gsub("unclear","Unknown",bed_file$V11)

#make a table of the families of TEs. How frequently do the different TE families appear in the genome?
table_of_TEs <- as.data.frame(table(bed_file$V11))

#remove simple repeats and unify "unknown" and "unclear"
table_of_TEs <- table_of_TEs[(!grepl("Low_complexity", table_of_TEs$Var1)),]
table_of_TEs <- table_of_TEs[(!grepl("Simple_repeat", table_of_TEs$Var1)),]

#create matrix with TE family frequency in the genome
cols.g <- rainbow(nrow(table_of_TEs))
table_of_TEs$percent = round(100*table_of_TEs$Freq/sum(table_of_TEs$Freq), digits = 1)
table_of_TEs$label = paste(table_of_TEs$Var1," (", table_of_TEs$percent,"%)", sep = "")
```

#Assess how the families breakdown for piRNA clusters
```{r, engine='bash'}
# Intersect cluster bedfile with TE bedfile
bedtools intersect -wo -a APUL_merged_cluster.bed -b APUL_repeatmasker_bedfile.bed > APUL_piRNA_cluster_TEs_intersect.txt

```

```{r}
#read in the output of bedtools intersect
cluster_TEs <- read.table("output/18.2-Apul-piRNA-TE-overlap/APUL_piRNA_clusters_TEs_intersect.txt")

#repeat analysis as above with piRNA cluster TEs
cluster_TEs$V8 <- gsub("/.*","",cluster_TEs$V8)
cluster_TEs$V8 <- gsub("unclear","Unknown",cluster_TEs$V8)
table_of_cluster_TEs <- as.data.frame(table(cluster_TEs$V8))
table_of_cluster_TEs <- table_of_cluster_TEs[(!grepl("Low_complexity", table_of_cluster_TEs$Var1)),]
table_of_cluster_TEs <- table_of_cluster_TEs[(!grepl("Simple_repeat", table_of_cluster_TEs$Var1)),]
cols <- rainbow(nrow(table_of_cluster_TEs))
table_of_cluster_TEs$percent = round(100*table_of_cluster_TEs$Freq/sum(table_of_cluster_TEs$Freq), digits = 1)
table_of_cluster_TEs$label = paste(table_of_cluster_TEs$Var1," (", table_of_cluster_TEs$percent,"%)", sep = "")

#generate stacked barplot showing TE distribution of clusters vs whole genome
table_of_TEs$origin <- "genome"
table_of_cluster_TEs$origin <- "cluster"
clust <- table_of_cluster_TEs[,c(5,1,3)]
genome <- table_of_TEs[,c(5,1,3)]
all <- rbind(clust, genome)
colnames(all)[2] <- "family"

# Stacked barplot
my.stack.out <- paste0("output/18.2-Apul-piRNA-TE-overlap/", my.outprefix,"cluster_stack_plot.pdf")
pdf(my.stack.out)
ggplot(all, aes(fill=family, y=percent, x=origin)) + 
  geom_bar(position="stack", stat="identity") + theme_bw()
dev.off()

#######################
sink(file = paste("output/18.2-Apul-piRNA-TE-overlap/", my.outprefix,"_session_Info.txt", sep =""))
sessionInfo()
sink()
```

